remote_theme: just-the-docs/just-the-docs
title: Mon Portfolio
description: BTS SIO SISR

# Active le mode sombre
color_scheme: dark
baseurl: "/Mon-Portfolio"

# Enlever : Table of contents
has_toc: false
